### PR TITLE
This is to assign the opcodes for the load extend instructions

### PR DESCRIPTION
**Pull request by rrwinterton**
This proposed change is to add the 6 load extend instructions for signed and unsigned integers using the naming convention suggested by others in the pull request https://github.com/WebAssembly/simd/issues/28

### CODE REVIEW

**Comment by tlively** [comment]
Should this be part of #77?

**Comment by penzn** [comment]
#77 has four of those (missing 32->64 operations)

**Comment by tlively** [comment]
Can we close this and add the extra instructions in #77, then?

**Comment by penzn** [comment]
@rrwinterton, @tlively, would something linke rrwinterton/simd#3 work?

**Comment by tlively** [comment]
Yes, that would be ideal. The discussion around these instructions is very spread out at the moment, and I think it would be good to concentrate all development and discussion on #77 so it is all in one place.

**Comment by penzn** [comment]
rrwinterton/simd#3 is merged, which populated #77, this can probably be closed now

**Pull request closed without merging**
