### PR TITLE
Sync simd tests from WAVM

### PR DESCRIPTION
**Pull request by Honry**

### CODE REVIEW

**Comment by Honry** [comment]
@arunetm, @tlively, PTAL, thanks!

**Comment by tlively** [comment]
Would it be possible to split this up into multiple PRs, each of which focuses on a small group of instructions? It would also be good to split out the python script changes.

**Comment by Honry** [comment]
@tlively, sure! :)

**Comment by Honry** [comment]
This PR has been split into https://github.com/WebAssembly/simd/pull/132, https://github.com/WebAssembly/simd/pull/133, https://github.com/WebAssembly/simd/pull/134, https://github.com/WebAssembly/simd/pull/135, https://github.com/WebAssembly/simd/pull/136, @tlively, @arunetm, PTAL, thanks!

**Comment by arunetm** [comment]
@Honry Can this PR be closed without merging as we already merged the others?

**Comment by Honry** [comment]
@arunetm, sure, close it.

**Pull request closed without merging**
