### PR TITLE
i64x2.abs instruction

### PR DESCRIPTION
**Pull request by Maratyszcza**
Introduction
=========

This is proposal to add 64-bit variant of existing `abs` instruction. ARM64 and x86 with AVX512 natively support this instruction, and on earlier instruction sets it can be emulated with 3-5 instructions.

Applications
========

- [simdpp SIMD wrapper library](https://github.com/p12tic/libsimdpp/blob/9dac213d6965bf57c7accf9dda6d16c3bed0e3ac/simdpp/detail/insn/i_abs.h#L211-L215)
- [Blaze SIMD wrapper library](https://bitbucket.org/blaze-lib/blaze/src/daf5b7cc2ef68d2a0b422594cde63c6c396b5a32/blaze/math/simd/Abs.h#lines-165:181)
- [DimSum SIMD wrapper library](https://github.com/google/dimsum/blob/f60cc12fdd3103170ba443672af135052d5b1ff5/simd_neon.h#L46-L49)
- [xsimd SIMD wrapper library](https://github.com/xtensor-stack/xsimd/blob/4dd2482908de2e90aa6b9ad004ae90036216a945/include/xsimd/types/xsimd_neon_int64.hpp#L418-L425)
- [Enoki vectorization & differentiation library](https://github.com/mitsuba-renderer/enoki/blob/ae3923759c637b244605e4948c8938f9da7be16b/include/enoki/array_neon.h#L1062-L1066)
- [KFR DSP library](https://github.com/kfrlib/kfr/blob/55e8c107122016518884e07ebe6b21704b27cb31/include/kfr/math/impl/abs.hpp#L94-L98)
- [SIMD Everywhere (SIMDe) polyfill library](https://github.com/simd-everywhere/simde/blob/b47f166cceb32255e67a1f600724c0bcda10cc93/simde/x86/avx512/abs.h#L408-L431)

Mapping to Common Instruction Sets
===========================

This section illustrates how the new WebAssembly instructions can be lowered on common instruction sets. However, these patterns are provided only for convenience, compliant WebAssembly implementations do not have to follow the same code generation patterns.

x86/x86-64 processors with AVX512F and AVX512VL instruction sets
--------------------------------------------------

- **i64x2.abs**
  - `y = i64x2.abs(x)` is lowered to `VPABSQ xmm_y, xmm_x`

x86/x86-64 processors with AVX instruction set
--------------------------------------------------

- **i64x2.abs**
  - `y = i64x2.abs(x)` (`x` is **not** `y`) is lowered to:
    - `VPXOR xmm_y, xmm_y, xmm_y`
    - `VPSUBQ xmm_y, xmm_y, xmm_x`
    - `VBLENDVPD xmm_y, xmm_x, xmm_y, xmm_x`

x86/x86-64 processors with SSE4.1 instruction set
--------------------------------------------------

- **i64x2.abs**
  - `y = i64x2.abs(x)` (`x` is **not** `y` and `x`/`y` is **not** in `xmm0`) is lowered to:
    - `PXOR xmm0, xmm0, xmm0`
    - `PSUBQ xmm0, xmm_x`
    - `MOVDQA xmm_y, xmm0`
    - `BLENDVPD xmm_y, xmm_x`

x86/x86-64 processors with SSE2 instruction set
--------------------------------------------------
- **i64x2.abs**
  - `y = i64x2.abs(x)` is lowered to:
    - `PSHUFD xmm_tmp, xmm_x, 0xF5`
    - `MOVDQA xmm_y, xmm_x`
    - `PSRAD xmm_tmp, 31`
    - `PSUBQ xmm_y, xmm_tmp`
    - `PXOR xmm_y, xmm_tmp`
  - `x = i64x2.abs(x)` is lowered to:
    - `PSHUFD xmm_tmp, xmm_x, 0xF5`
    - `PSRAD xmm_tmp, 31`
    - `PSUBQ xmm_x, xmm_tmp`
    - `PXOR xmm_x, xmm_tmp`

ARM64 processors
--------------------------------------------------
- **i64x2.abs**
  - `y = i64x2.abs(a, b)` is lowered to `ABS Vy.2D, Vx.2D`

ARMv7 processors with NEON instruction set
--------------------------------------------------
- **i64x2.abs**
  - `y = i64x2.abs(a, b)` is lowered to:
    - `VSHR.S64 Qtmp, Qx, #63`
    - `VSUB.I64 Qy, Qx, Qtmp`
    - `VEOR Qy, Qy, Qtmp`

### CODE REVIEW

**Comment by jan-wassenberg** [comment]
Strong support, I'm adding this to Highway as well. It would be much harder for users to emulate this, especially if we do not add sign select nor i64 gt_s.

**Comment by dtig** [comment]
Adding a preliminary vote for the inclusion of i64x2.abs operation to the SIMD proposal below. Please vote with -

👍 For including i64x2.abs
👎 Against including i64x2.abs

**Comment by penzn** [comment]
I do have an issue with examples here - they seem to be all wrapper libraries. It isn't surprising that wrapper libraries would ave all sorts of operations, but this isn't the same as an app somebody could run.

**Comment by Maratyszcza** [comment]
Fixed a bug in suggested lowering on SSE2 and ARM NEON (thanks @ngzhian for reporting).

**Pull request merged**
