### PR TITLE
Update SpiderMonkey status

### PR DESCRIPTION
**Pull request by lars-t-hansen**
New instructions are now in Nightly for x86 and x64, and for arm64 with the baseline compiler.

### CODE REVIEW

**Review by ngzhian — APPROVED** [review]
Nice, LGTM!

**Comment by lars-t-hansen** [comment]
@ngzhian, can you merge?  i don't have the right.

**Comment by ngzhian** [comment]
Oh weird, sorry I assumed you could do it. And I'm too slow, there are now merge conflicts, can you resolve them please?

**Comment by lars-t-hansen** [comment]
I'll file a new PR next week, we have a new batch of instructions coming.

**Pull request closed without merging**
