### PR TITLE
[test] Sync tests from WAVM#223

### PR DESCRIPTION
**Pull request by Honry**
https://github.com/WAVM/WAVM/pull/223

    [simd] Improve simd test generation tool

    - Use names in the string interpolation so its clear
      what each part is supposed to be.
    - Use unified naming converson for params.

### CODE REVIEW

**Comment by Honry** [comment]
@arunetm, @tlively, PTAL, thanks!

**Comment by abrown** [comment]
Is this only renaming of variables or are there functionality changes? Could you point to the functionality changes, if any? I can't see them 😄.

**Comment by Honry** [comment]
@abrown, no functionality changes here, just try to make the naming convention consistent.

**Comment by Honry** [comment]
Friendly ping. :)

**Pull request merged**
