### PR TITLE
Add SIMD instructions to index of instructions

### PR DESCRIPTION
**Pull request by ngzhian**
Depends on #340.

Preview at https://www.ngzhian.com/simd/core/appendix/index-instructions.html note how rows with "execution, operator" in the last column are now taller. This is unfortunate due to how long some of the SIMD instructions are.

### CODE REVIEW

**Comment by binji** [comment]
Did you use the [`gen-index-instructions.py`](https://github.com/WebAssembly/spec/blob/master/document/core/appendix/gen-index-instructions.py) script, or do it by hand?

**Review by binji — APPROVED** [review]
table lgtm, though I mostly did a spot check. It's a bit sad about the columns, but I think it's OK. Maybe we can tweak it a bit later.

**Comment by ngzhian** [comment]
I forgot about gen-index-instructions.py... I'll fix it.

**Comment by ngzhian** [comment]
First I'll need to merge upstream.

**Comment by ngzhian** [comment]
Replaced by #366

**Pull request closed without merging**
